apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

// Firebase
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

Properties secureProps = new Properties()
secureProps.load(new FileInputStream(rootProject.file("env.properties")))

android {
    compileSdk = 36

    signingConfigs {
        debug {
            storeFile file('/Users/gameboy/Downloads/apkkey.jks')
            storePassword secureProps['debug.store.password']
            keyAlias secureProps['debug.store.key.alias']
            keyPassword secureProps['debug.store.key.password']
        }
        prod {
            storeFile file('/Users/gameboy/Downloads/smart-accounting.jks')
            storePassword secureProps['prod.store.password']
            keyAlias secureProps['prod.store.key.alias']
            keyPassword secureProps['prod.store.key.password']
        }
    }

    defaultConfig {
        applicationId "help.smartbusiness.smartaccounting"
        minSdk = 23
        targetSdk = 36
        versionCode 9
        versionName "1.5"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.prod
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding true
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/license.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt', 'META-INF/notice.txt', 'META-INF/ASL2.0']
        }
    }
    namespace 'help.smartbusiness.smartaccounting'
}

configurations {
    all {
        exclude module: 'httpclient'
    }
}

repositories{
    maven { url "https://jitpack.io" }
    mavenCentral()
}

dependencies {
    // Core
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.gms:play-services-auth:21.4.0'
    implementation 'com.google.http-client:google-http-client-gson:1.26.0'
    implementation('com.google.api-client:google-api-client-android:1.26.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    implementation('com.google.apis:google-api-services-drive:v3-rev136-1.25.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    implementation "androidx.core:core-ktx:1.15.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    // UI
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.3.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.getbase:floatingactionbutton:1.10.1'
    implementation 'com.github.BlacKCaT27:CurrencyEditText:v1.4.4'
    implementation 'com.github.prolificinteractive:material-calendarview:2.0.0'
    implementation 'com.jakewharton.threetenabp:threetenabp:1.2.0'

    // https://stackoverflow.com/a/60492942
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.14.2'

    // Notifications
    implementation "io.karn:notify:1.3.0"

    // Monitoring
    implementation platform('com.google.firebase:firebase-bom:34.2.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    androidTestImplementation 'androidx.test:core:1.7.0'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
}
